compile: Course.java Faculty.java Participant.java Stcm.java
	javac Course.java Faculty.java Participant.java Stcm.java
	@echo "Compilation completed!\nRun the proogram by typing \
	'java src.Stcm' from parent folder"
clean: 
	rm *.class
